### ISSUE TITLE
Request to release npm package

### ISSUE THREAD

**Issue by lukew3** [yeungon/math#2]
Hey, I saw that you created the [math-generator package on npm](https://www.npmjs.com/package/math-generator). I'm creating my own js implementation of my original python [mathgenerator](https://github.com/lukew3/mathgenerator) and would like to use the same mathgenerator name for an npm package. Npm thinks that math-generator and mathgenerator are too similar so I can't create a package with the name mathgenerator. Could you release this by changing the name of your package or removing it from npm? 

I'm currently developing on the [js branch](https://www.npmjs.com/package/math-generator) if you want to see what I'm working on or are interested in contributing anything of your own.

Thanks,
lukew3

**Comment by yeungon** [comment]
Hi @lukew3. I like your idea pretty much and I am happy that you are writing another version in JS. Let's me find the way to change the name first before you can use that.

I am gonna keep porting your package into JS in my own way, just for fun :v: 

Will mention you here when it is done.

**Comment by yeungon** [comment]
hi @lukew3 you can now take the package name as I have changed from https://www.npmjs.com/package/math-generator to https://www.npmjs.com/package/@yeungon/math-generator

Cheer.

**Comment by lukew3** [comment]
Thanks!
